<?php

// $Id$

/**
 * @file
 * Displays the nearest galleries to this gallery
 */


/**
 * Implementation of hook_block()
 */
function nearby_block($op='list', $delta=0, $edit=array()) {
   global $node;
  switch ($op) {
   case 'list':
      $blocks[0]['info'] = t('Nearby galleries');
      return $blocks;

   case 'view':
              // is this a node?
        if (arg(0) != 'node')
         break;
   
        if (!is_numeric(arg(1)) && arg(1) != 'add')
         break;

        if (is_numeric(arg(1))) {
            $node = node_load(arg(1));

       if($node -> type == 'gallery' && count($node -> locations) > 0)
       {
          if($node->locations[0]['latitude'] == 0 && $node->locations[0]['longitude'] == 0)
                  break;
         $thisnode = $node -> nid;
         $latlon_query = " SELECT latitude, longitude FROM `drupal_location` WHERE lid IN (
                           SELECT lid FROM drupal_location_instance WHERE nid = $thisnode)";
         $results = db_query($latlon_query);
         while($data = db_fetch_array($results))
         {
            $latitude = $data['latitude'];
            $longitude = $data['longitude'];
         }
         $display_content = '';

         $query = "SELECT nid,((ACOS(SIN($latitude * PI() / 180) *
            SIN(latitude * PI() / 180) + COS($latitude * PI() / 180) *
            COS(latitude * PI() / 180) * COS(($longitude - longitude) * PI() / 180))
             * 180 / PI()) * 60 * 1.1515)
            AS distance
         FROM drupal_location
            LEFT JOIN drupal_location_instance on drupal_location. lid = drupal_location_instance.lid
            WHERE nid <> $thisnode
         AND nid IN (SELECT nid FROM drupal_node WHERE status = 1)
            ORDER BY distance ASC LIMIT 1,10";


//         $query = "SELECT nid,
//         (
//         acos(sin(deg2rad($lat1))
//              * sin(deg2rad($lat2))
//              + cos(deg2rad($lat1))
//              * cos(deg2rad($lat2))
//              * cos(deg2rad($lon1 - $lon2)));
//
//    $dist   = rad2deg($dist);
//    $miles  = (float) $dist * 69;
//
//         )
//         AS distance
//         FROM drupal_location
//            LEFT JOIN drupal_location_instance on drupal_location. lid = drupal_location_instance.lid
//            WHERE nid <> $thisnode
//         AND nid IN (SELECT nid FROM drupal_node WHERE status = 1)
//            ORDER BY distance ASC LIMIT 1,10";

         $galleries = db_query($query);
         for($i = 0; $i < 10; $i++)
         {
            $data = db_fetch_array($galleries);
            $gallery = node_load($data['nid']);
            $display_content .= '<div class="link">'.
               l($gallery -> title, $gallery -> path). '<br/>'.
               number_format($data['distance'],1).' miles</div>';
         }
      $block['subject'] = t('Nearby galleries');
      $block['content'] = $display_content;
      return $block;
      }

   }
}
}